                highways_all AS -- this is a simplified version without the different line endings for open end roads
                (WITH highways_ends AS
                  (SELECT
                        way,
                        way_orig,
                        clip,
                        feature,
                        highway,
                        path_type,
                        int_surface,
                        int_tunnel,
                        int_bridge,
                        int_lane_right,
                        int_lane_left,
                        int_lanes,
                        int_side_right,
                        int_side_left,
                        int_access,
                        construction,
                        service,
                        link,
                        width_lane,
                        width_lane_cycle,
                        width_nominal,
                        width_tagged,
                        casing_width,
                        length_px,
                        layernotnull,
                        osm_id,
                        z_order
                  FROM
                    (SELECT
                        way,
                        way_orig,
                        clip,
                        feature,
                        highway,
                        path_type,
                        int_surface,
                        int_tunnel,
                        int_bridge,
                        int_lane_right,
                        int_lane_left,
                        int_lanes,
                        int_side_right,
                        int_side_left,
                        int_access,
                        construction,
                        service,
                        link,
                        width_lane,
                        width_lane_cycle,
                        width_nominal,
                        width_tagged,
                        width_max,
                        casing_width,
                        length_px,
                        layernotnull,
                        osm_id,
                        z_order
                      FROM
                        (SELECT
                            way,
                            way_orig,
                            clip,
                            feature,
                            highway,
                            path_type,
                            int_surface,
                            int_tunnel,
                            int_bridge,
                            int_lane_right,
                            int_lane_left,
                            int_lanes,
                            int_side_right,
                            int_side_left,
                            int_access,
                            construction,
                            service,
                            link,
                            width_lane,
                            width_lane_cycle,
                            width_nominal,
                            width_tagged,
                            width_max,
                            casing_width,
                            ST_Length(way)/NULLIF(!scale_denominator!*0.001*0.28,0) AS length_px,
                            layernotnull,
                            osm_id,
                            z_order
                          FROM
                            (SELECT
                                ST_Difference(
                                  h.way,
                                  COALESCE(
                                    j.bounds,
                                    ST_SetSRID('GEOMETRYCOLLECTION EMPTY'::geometry, 3857)
                                  )
                                ) AS way,
                                h.way AS way_orig,
                                j.clip AS clip,
                                h.feature AS feature,
                                h.highway AS highway,
                                h.path_type AS path_type,
                                h.int_surface AS int_surface,
                                h.int_tunnel AS int_tunnel,
                                h.int_bridge AS int_bridge,
                                h.int_lane_right AS int_lane_right,
                                h.int_lane_left AS int_lane_left,
                                h.int_lanes AS int_lanes,
                                h.int_side_right AS int_side_right,
                                h.int_side_left AS int_side_left,
                                h.int_access AS int_access,
                                h.construction AS construction,
                                h.service AS service,
                                h.link AS link,
                                h.width_lane AS width_lane,
                                h.width_lane_cycle AS width_lane_cycle,
                                h.width_nominal AS width_nominal,
                                h.width_tagged AS width_tagged,
                                GREATEST(h.width_nominal, h.width_tagged) AS width_max,
                                carto_casing_line_width(h.highway, h.int_bridge, z(!scale_denominator!)) AS casing_width,
                                h.layernotnull AS layernotnull,
                                h.osm_id AS osm_id,
                                h.z_order AS z_order
                              FROM highways_raw h
                              LEFT JOIN
                                (SELECT
                                    ST_Union(bounds) AS bounds,
                                    ST_Union(clip) AS clip,
                                    osm_id
                                  FROM junctions GROUP BY osm_id
                                ) AS j
                                ON j.osm_id = h.osm_id
                            ) AS hwj2
                        ) AS hwj
                    ) AS _
                  )
                SELECT
                    way,
                    way_orig,
                    NULL::GEOMETRY AS way_ext,
                    clip,
                    feature,
                    highway,
                    path_type,
                    int_surface,
                    int_tunnel,
                    int_bridge,
                    int_lane_right,
                    int_lane_left,
                    int_lanes,
                    int_side_right,
                    int_side_left,
                    int_access,
                    construction,
                    service,
                    link,
                    NULL as connect_type,
                    width_lane,
                    width_lane_cycle,
                    width_nominal,
                    width_tagged,
                    casing_width,
                    layernotnull,
                    osm_id,
                    z_order
                  FROM highways_ends
                ), -- end highways_all CTE
