-- These is the z_order table for roads rendering in OpenStreetMap Carto Alternative Colors.
-- This file is generated with scripts/z_order.py
DROP TABLE IF EXISTS "carto_z_order";
CREATE TABLE "carto_z_order"
  (feature TEXT PRIMARY KEY, z_order INTEGER);
INSERT INTO "carto_z_order" (feature, z_order) VALUES
  ('highway_motorway', 380),
  ('highway_trunk', 370),
  ('highway_primary', 360),
  ('highway_secondary', 350),
  ('highway_tertiary', 340),
  ('highway_unclassified', 330),
  ('highway_residential', 330),
  ('highway_bus_guideway', 320),
  ('highway_busway', 320),
  ('highway_living_street', 310),
  ('highway_pedestrian', 300),
  ('highway_road', 290),
  ('highway_raceway', 280),
  ('highway_motorway_link', 270),
  ('highway_trunk_link', 260),
  ('highway_primary_link', 250),
  ('highway_secondary_link', 240),
  ('highway_tertiary_link', 230),
  ('highway_service', 190),
  ('highway_track', 110),
  ('highway_path', 100),
  ('highway_footway', 100),
  ('highway_cycleway', 100),
  ('highway_bridleway', 100),
  ('highway_steps', 90),
  ('highway_platform', 80),
  ('railway_rail', 440),
  ('railway_subway', 420),
  ('railway_narrow_gauge', 420),
  ('railway_light_rail', 420),
  ('railway_funicular', 420),
  ('railway_preserved', 420),
  ('railway_monorail', 420),
  ('railway_miniature', 420),
  ('railway_turntable', 420),
  ('railway_tram', 410),
  ('railway_disused', 400),
  ('railway_construction', 400),
  ('railway_platform', 80),
  ('aeroway_runway', 60),
  ('aeroway_taxiway', 50);
